#!/usr/bin/env bash
set -e

usage() {
  echo "$(basename $0) <on|off>"
}


# sanity checks
[[ $(uname -s) == Darwin ]] || { echo "Aborting, You're not running macOS."; exit 2; }


# options
GIT_HTTP=http://*.git.example.com
GIT_HTTPS=https://*.git.example.com
NETWORKSVC="Wi-Fi"                                  # Run `networksetup -listallnetworkservices` for the list.
LOCALPORT="8888"                                    # Local port to bind.
REMOTEHOST="YOURREMOTEHOST"                         # Your bastion host.
TUNNEL="ssh -f -N -D ${LOCALPORT} -C ${REMOTEHOST}"


# setup
# System Preferences > Network > [Interface] > Advanced... > Proxies > SOCKS Proxy
networksetup -setsocksfirewallproxy ${NETWORKSVC} localhost ${LOCALPORT}


# main
# create/destroy ssh tunnel and modify ~/.gitconfig
TOGGLE=${1}
case ${TOGGLE} in
  on)
      lsof -i4:${LOCALPORT} || \
      timeout 5 ${TUNNEL} 2>/dev/null && \
      git config --file ${HOME}/.gitconfig http.${GIT_HTTP}.proxy "socks5://127.0.0.1:${LOCALPORT}" && \
      git config --file ${HOME}/.gitconfig https.${GIT_HTTPS}.proxy "socks5://127.0.0.1:${LOCALPORT}" || \
      { echo error; exit 2; } \
      ;;
  off)
      pkill -KILL -f "${TUNNEL}" && \
      git config --file ${HOME}/.gitconfig --remove-section http.${GIT_HTTP} && \
      git config --file ${HOME}/.gitconfig --remove-section https.${GIT_HTTPS} || \
      { echo error; exit 2; } \
      ;;
  *)
      usage
      exit 1
      ;;
esac


# toggle switch
networksetup -setsocksfirewallproxystate ${NETWORKSVC} ${TOGGLE}


# verbose
networksetup -getsocksfirewallproxy ${NETWORKSVC}
